export default {
  SET_USER: "SET_USER",
  CLEAR_USER: "CLEAR_USER",
  ADD_GROUP: "ADD_GROUP",
  START_LOADING: "START_LOADING",
  STOP_LOADING: "STOP_LOADING",
  SET_ERROR: "SET_ERROR",
  SET_RESTAURANTS: "SET_RESTAURANTS",
  REFRESH_RESTAURANTS: "REFRESH_RESTAURANTS",
  SET_FILTERS: "SET_FILTERS",
  SET_SORT: "SET_SORT",
  SET_GROUP: "SET_GROUP",
};
